### ISSUE TITLE
Pycirkuit crashes when run

### ISSUE THREAD

**Issue by aniolm9** [orestesmas/pycirkuit#12]
### System information
Debian 9.7
Python 3.5.3

### Expected behaviour
The program to run.

### Actual behaviour
Pycirkuit crashes with the following error:

```
Traceback (most recent call last):
  File "PyCirkuit/bin/pycirkuit", line 11, in <module>
    load_entry_point('pycirkuit==0.2b1', 'gui_scripts', 'pycirkuit')()
  File "/opt/pycirkuit/PyCirkuit/lib/python3.5/site-packages/pycirkuit/main.py", line 30, in main
    from pycirkuit.mainwindow import MainWindow
  File "/opt/pycirkuit/PyCirkuit/lib/python3.5/site-packages/pycirkuit/mainwindow.py", line 33, in <module>
    from pycirkuit.configdialog import ConfigDialog
  File "/opt/pycirkuit/PyCirkuit/lib/python3.5/site-packages/pycirkuit/configdialog.py", line 38, in <module>
    from exceptions import PyCirkuitError
ImportError: No module named 'exceptions'
```

### Reproduce the behaviour
Just install the last version and try to run it.

**Comment by orestesmas** [comment]
Closed by 3ac385ddf81140304b8838dab16a80125ab9bd63
