### ISSUE TITLE
Pycirkuit crashes when setting a directory in LaTeX Template File

### ISSUE THREAD

**Issue by aniolm9** [orestesmas/pycirkuit#8]
### System information
Debian 9.7
Python 3.5.3

### Expected behaviour
An error window should be displayed saying that setting a directory is not allowed.

### Actual behaviour
Pycirkuit crashes with the following error:

```
Traceback (most recent call last):
  File "/opt/pycirkuit/venv/lib/python3.5/site-packages/pycirkuit/mainwindow.py", line 411, in on_processButton_clicked
    if not self._check_templates():
  File "/opt/pycirkuit/venv/lib/python3.5/site-packages/pycirkuit/mainwindow.py", line 134, in _check_templates
    with open(template, 'r') as t:
IsADirectoryError: [Errno 21] Is a directory: '/opt/pycirkuit/venv/lib/python3.5/site-packages/pycirkuit/templates'
```

### Reproduce the behaviour
Set a directory in the field _LaTeX Template File_. Then, click the button _Process and display_.

**Comment by aniolm9** [comment]
This bug seems to be fixed in develop, I'm closing it.
